name: Test
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup-pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - name: run-tests
        run: pnpm test
